spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
server:
  port: 9080
management:
  endpoints:
    web:
      exposure:
        include: "*"